"""North American wildlife."""

ALL = [
    "Bald eagle",
    "American bison",
    "Grizzly bear",
    "American black bear",
    "Bobcat",
    "Cougar",
    "Coyote",
    "Gray wolf",
    "Pronghorn",
    "Moose",
    "American alligator",
    "Bighorn sheep",
    "Raccoon",
    "Red fox",
    "Wild turkey",
    "American beaver",
    "Manatee",
    "Roadrunner",
    "River otter",
    "American flamingo",
    "California sea lion",
    "Florida panther",
]

# Display name -> English Wikipedia article title.
WIKIPEDIA = {
    "Bald eagle": "Bald eagle",
    "American bison": "American bison",
    "Grizzly bear": "Grizzly bear",
    "American black bear": "American black bear",
    "Bobcat": "Bobcat",
    "Cougar": "Cougar",
    "Coyote": "Coyote",
    "Gray wolf": "Wolf",
    "Pronghorn": "Pronghorn",
    "Moose": "Moose",
    "American alligator": "American alligator",
    "Bighorn sheep": "Bighorn sheep",
    "Raccoon": "Raccoon",
    "Red fox": "Red fox",
    "Wild turkey": "Wild turkey",
    "American beaver": "North American beaver",
    "Manatee": "Manatee",
    "Roadrunner": "Roadrunner",
    "River otter": "North American river otter",
    "American flamingo": "American flamingo",
    "California sea lion": "California sea lion",
    "Florida panther": "Florida panther",
}

# Display name -> scientific name (shown as tag on reveal).
SCIENTIFIC_NAMES = {
    "Bald eagle": "Haliaeetus leucocephalus",
    "American bison": "Bison bison",
    "Grizzly bear": "Ursus arctos horribilis",
    "American black bear": "Ursus americanus",
    "Bobcat": "Lynx rufus",
    "Cougar": "Puma concolor",
    "Coyote": "Canis latrans",
    "Gray wolf": "Canis lupus",
    "Pronghorn": "Antilocapra americana",
    "Moose": "Alces alces",
    "American alligator": "Alligator mississippiensis",
    "Bighorn sheep": "Ovis canadensis",
    "Raccoon": "Procyon lotor",
    "Red fox": "Vulpes vulpes",
    "Wild turkey": "Meleagris gallopavo",
    "American beaver": "Castor canadensis",
    "Manatee": "Trichechus",
    "Roadrunner": "Geococcyx",
    "River otter": "Lontra canadensis",
    "American flamingo": "Phoenicopterus ruber",
    "California sea lion": "Zalophus californianus",
    "Florida panther": "Puma concolor coryi",
}
