"""North American wildlife."""

ALL = [
    "Bald eagle",
    "American bison",
    "Grizzly bear",
    "American black bear",
    "Bobcat",
    "Cougar",
    "Coyote",
    "Gray wolf",
    "Pronghorn",
    "Moose",
    "American alligator",
    "Bighorn sheep",
    "Raccoon",
    "Red fox",
    "Wild turkey",
    "American beaver",
    "Manatee",
    "Roadrunner",
    "River otter",
    "American flamingo",
    "California sea lion",
    "Florida panther",
]

# Display name -> English Wikipedia article title.
WIKIPEDIA = {
    "Bald eagle": "Bald eagle",
    "American bison": "American bison",
    "Grizzly bear": "Grizzly bear",
    "American black bear": "American black bear",
    "Bobcat": "Bobcat",
    "Cougar": "Cougar",
    "Coyote": "Coyote",
    "Gray wolf": "Wolf",
    "Pronghorn": "Pronghorn",
    "Moose": "Moose",
    "American alligator": "American alligator",
    "Bighorn sheep": "Bighorn sheep",
    "Raccoon": "Raccoon",
    "Red fox": "Red fox",
    "Wild turkey": "Wild turkey",
    "American beaver": "North American beaver",
    "Manatee": "Manatee",
    "Roadrunner": "Roadrunner",
    "River otter": "North American river otter",
    "American flamingo": "American flamingo",
    "California sea lion": "California sea lion",
    "Florida panther": "Florida panther",
}
