"""Iconic US landscapes — national parks, canyons, rivers, mountains."""

ALL = [
    "Grand Canyon",
    "Yellowstone",
    "Yosemite",
    "Niagara Falls",
    "Death Valley",
    "Everglades",
    "Monument Valley",
    "Glacier National Park",
    "Crater Lake",
    "Denali",
    "Mount Rainier",
    "Joshua Tree National Park",
    "Bryce Canyon",
    "Zion National Park",
    "Acadia National Park",
    "Arches National Park",
    "Mammoth Cave",
    "Great Smoky Mountains",
    "Mississippi River",
    "Mojave Desert",
    "Hawaiʻi Volcanoes",
    "Rocky Mountains",
]

# Display name -> US state abbreviation(s) (shown as tag on reveal).
# Two-letter codes keep tags uniform (see monuments.py for the regex
# rationale). Skipped for very multi-state features (Mississippi River,
# Rocky Mountains).
LOCATIONS = {
    "Grand Canyon": "AZ",
    "Yellowstone": "WY",
    "Yosemite": "CA",
    "Niagara Falls": "NY",
    "Death Valley": "CA",
    "Everglades": "FL",
    "Monument Valley": "AZ–UT",
    "Glacier National Park": "MT",
    "Crater Lake": "OR",
    "Denali": "AK",
    "Mount Rainier": "WA",
    "Joshua Tree National Park": "CA",
    "Bryce Canyon": "UT",
    "Zion National Park": "UT",
    "Acadia National Park": "ME",
    "Arches National Park": "UT",
    "Mammoth Cave": "KY",
    "Great Smoky Mountains": "TN–NC",
    "Mojave Desert": "CA–NV",
    "Hawaiʻi Volcanoes": "HI",
}

# Display name -> English Wikipedia article title.
WIKIPEDIA = {
    "Grand Canyon": "Grand Canyon",
    "Yellowstone": "Yellowstone National Park",
    "Yosemite": "Yosemite National Park",
    "Niagara Falls": "Niagara Falls",
    "Death Valley": "Death Valley",
    "Everglades": "Everglades",
    "Monument Valley": "Monument Valley",
    "Glacier National Park": "Glacier National Park (U.S.)",
    "Crater Lake": "Crater Lake",
    "Denali": "Denali",
    "Mount Rainier": "Mount Rainier",
    "Joshua Tree National Park": "Joshua Tree National Park",
    "Bryce Canyon": "Bryce Canyon National Park",
    "Zion National Park": "Zion National Park",
    "Acadia National Park": "Acadia National Park",
    "Arches National Park": "Arches National Park",
    "Mammoth Cave": "Mammoth Cave National Park",
    "Great Smoky Mountains": "Great Smoky Mountains National Park",
    "Mississippi River": "Mississippi River",
    "Mojave Desert": "Mojave Desert",
    "Hawaiʻi Volcanoes": "Hawaiʻi Volcanoes National Park",
    "Rocky Mountains": "Rocky Mountains",
}
