"""Iconic US monuments and landmarks."""

ALL = [
    "Statue of Liberty",
    "Empire State Building",
    "Mount Rushmore",
    "White House",
    "Lincoln Memorial",
    "Washington Monument",
    "US Capitol",
    "Brooklyn Bridge",
    "Golden Gate Bridge",
    "Space Needle",
    "Gateway Arch",
    "Hollywood Sign",
    "Independence Hall",
    "Liberty Bell",
    "The Pentagon",
    "Mount Vernon",
    "Monticello",
    "Vietnam Veterans Memorial",
    "Jefferson Memorial",
    "The Alamo",
    "Times Square",
    "Willis Tower",
    "Cinderella Castle",
    "Wrigley Field",
    "Fenway Park",
    "Hoover Dam",
    "USS Arizona Memorial",
    "One World Trade Center",
]

# Display name -> English Wikipedia article title.
WIKIPEDIA = {
    "Statue of Liberty": "Statue of Liberty",
    "Empire State Building": "Empire State Building",
    "Mount Rushmore": "Mount Rushmore",
    "White House": "White House",
    "Lincoln Memorial": "Lincoln Memorial",
    "Washington Monument": "Washington Monument",
    "US Capitol": "United States Capitol",
    "Brooklyn Bridge": "Brooklyn Bridge",
    "Golden Gate Bridge": "Golden Gate Bridge",
    "Space Needle": "Space Needle",
    "Gateway Arch": "Gateway Arch",
    "Hollywood Sign": "Hollywood Sign",
    "Independence Hall": "Independence Hall",
    "Liberty Bell": "Liberty Bell",
    "The Pentagon": "The Pentagon",
    "Mount Vernon": "Mount Vernon",
    "Monticello": "Monticello",
    "Vietnam Veterans Memorial": "Vietnam Veterans Memorial",
    "Jefferson Memorial": "Jefferson Memorial",
    "The Alamo": "Alamo Mission in San Antonio",
    "Times Square": "Times Square",
    "Willis Tower": "Willis Tower",
    "Cinderella Castle": "Cinderella Castle",
    "Wrigley Field": "Wrigley Field",
    "Fenway Park": "Fenway Park",
    "Hoover Dam": "Hoover Dam",
    "USS Arizona Memorial": "USS Arizona Memorial",
    "One World Trade Center": "One World Trade Center",
}
